const PAYTM_TRANSACTION_URL = 'https://securegw-stage.paytm.in/order/process';
const PAYTM_TRANSACTION_STATUS_URL = 'https://securegw-stage.paytm.in/order/status';
const MID = 'PAYTM_MERCHANT_ID';
const PAYTM_MERCHANT_KEY = 'PAYTM_MERCHANT_KEY';
const WEBSITE = 'WEBSTAGING';
const INDUSTRY_TYPE_ID = 'RETAIL';
const CHANNEL_ID = 'WEB';

const config = {
  PAYTM_TRANSACTION_URL: PAYTM_TRANSACTION_URL,
  PAYTM_TRANSACTION_STATUS_URL: PAYTM_TRANSACTION_STATUS_URL,
  MID: MID,
  PAYTM_MERCHANT_KEY: PAYTM_MERCHANT_KEY,
  WEBSITE: WEBSITE,
  INDUSTRY_TYPE_ID: INDUSTRY_TYPE_ID,
  CHANNEL_ID: CHANNEL_ID
}

module.exports = config;